{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPa30U4cHrntIqVHjmRUPpd"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "pip install faiss-cpu"
      ],
      "metadata": {
        "id": "LCDUA7Wvi821"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import faiss\n",
        "import numpy as np\n",
        "import nltk\n",
        "from transformers import pipeline\n",
        "from nltk.corpus import stopwords\n",
        "from nltk.tokenize import word_tokenize\n",
        "from sentence_transformers import SentenceTransformer\n",
        "\n",
        "nltk.download('punkt_tab')\n",
        "nltk.download('stopwords')\n",
        "\n",
        "\n",
        "class SimpleRAG:\n",
        "\n",
        "    def __init__(self):\n",
        "        # Load embedding model\n",
        "        self.model = SentenceTransformer('all-MiniLM-L6-v2')\n",
        "        self.stop_words = set(stopwords.words('english'))\n",
        "        self.index = None\n",
        "        self.documents = []\n",
        "\n",
        "    # Step 1 & 2: Preprocess Data (Remove Stopwords)\n",
        "    def preprocess(self, text):\n",
        "        words = word_tokenize(text)\n",
        "        filtered = [w for w in words if w.lower() not in self.stop_words]\n",
        "        return \" \".join(filtered)\n",
        "\n",
        "    # Step 3: Convert to Embeddings\n",
        "    def embed(self, texts):\n",
        "        return self.model.encode(texts)\n",
        "\n",
        "    # Step 4: Store in Vector DB\n",
        "    def store_documents(self, documents):\n",
        "        self.documents = [self.preprocess(doc) for doc in documents]\n",
        "        embeddings = self.embed(self.documents)\n",
        "\n",
        "        dimension = embeddings.shape[1]\n",
        "        self.index = faiss.IndexFlatL2(dimension)\n",
        "        self.index.add(np.array(embeddings))\n",
        "\n",
        "    # Step 5: Search Similar Documents\n",
        "    def search(self, query, k=2):\n",
        "        processed_query = self.preprocess(query)\n",
        "        query_vector = self.embed([processed_query])\n",
        "\n",
        "        distances, indices = self.index.search(query_vector, k)\n",
        "        results = [self.documents[i] for i in indices[0]]\n",
        "        return results\n",
        "\n",
        "    # Step 6: Generate Answer (Simple LLM Simulation)\n",
        "    def generate_answer(self, query):\n",
        "        generator = pipeline('text-generation',model='gpt2')\n",
        "        retrieved_docs = self.search(query)\n",
        "\n",
        "        context = \" \".join(retrieved_docs)\n",
        "\n",
        "      # Simple generation (replace with real LLM if needed)\n",
        "        answer = f\"Based on the documents, the answer is:\\n{context}\"\n",
        "        # Generate answer\n",
        "        result = generator(answer, max_length=150, num_return_sequences=1)\n",
        "        return result\n",
        "# Sample Data\n",
        "documents = [\n",
        "    \"Machine Learning (ML) is a subfield of Artificial Intelligence concerned with designing algorithms that enable systems to learn patterns from data and make decisions or predictions without being explicitly programmed with rule-based logic. Instead of hard-coding instructions, ML models infer functional relationships between input features (independent variables) and target outputs (dependent variables) by optimizing an objective function over training data. At its core, ML is about **statistical estimation, optimization, and generalization**. A model is trained on historical data using an algorithm (e.g., gradient descent), where parameters are iteratively adjusted to minimize a loss function such as Mean Squared Error (regression) or Cross-Entropy (classification). The ultimate goal is not just memorizing training data but achieving strong performance on unseen data — this ability is called generalization.\",\n",
        "    \"Machine Learning is broadly categorized into **Supervised Learning**, **Unsupervised Learning**, and **Reinforcement Learning**. In supervised learning, labeled datasets are used to train models for tasks such as regression (predicting continuous values like house prices) and classification (predicting categories like spam vs non-spam). Algorithms such as Linear Regression, Logistic Regression, Decision Trees, Random Forests, Support Vector Machines, and Neural Networks are commonly used. In unsupervised learning, the data has no labeled target variable, and the goal is to uncover hidden structures or patterns, such as clustering customers using K-Means or reducing dimensionality using PCA. Reinforcement learning, on the other hand, focuses on agents interacting with an environment, learning optimal strategies through reward-based feedback mechanisms, widely applied in robotics and game AI.\",\n",
        "    \"A typical ML pipeline includes data collection, data preprocessing (handling missing values, encoding categorical variables, scaling features), feature engineering, model selection, hyperparameter tuning (e.g., using GridSearchCV), model evaluation (using metrics like Accuracy, F1-score, ROC-AUC for classification or RMSE and R² for regression), and deployment. Overfitting and underfitting are key concerns; regularization techniques such as L1 (Lasso) and L2 (Ridge) penalties help control model complexity. Cross-validation is used to ensure robust evaluation. In production systems, considerations expand to model drift, scalability, monitoring, and reproducibility.\",\n",
        "    \"Modern ML has evolved significantly with the advancement of Deep Learning, where multi-layer neural networks automatically learn hierarchical feature representations from large-scale datasets. Applications of ML span across industries — recommendation systems (e-commerce), fraud detection (finance), predictive maintenance (manufacturing), NLP (chatbots, sentiment analysis), computer vision (image recognition), healthcare diagnostics, and autonomous vehicles. Ultimately, Machine Learning transforms raw data into actionable intelligence by leveraging mathematical modeling, probability theory, and computational efficiency to automate decision-making at scale.\"\n",
        "]\n",
        "\n",
        "# Create object\n",
        "rag = SimpleRAG()\n",
        "\n",
        "# Store data\n",
        "rag.store_documents(documents)\n",
        "\n",
        "# User Query\n",
        "query = \"What is artificial intelligence?\"\n",
        "\n",
        "# Generate Answer\n",
        "print(rag.generate_answer(query))"
      ],
      "metadata": {
        "id": "16JjkQK1j1J7"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import faiss\n",
        "import numpy as np\n",
        "import nltk\n",
        "from transformers import pipeline\n",
        "from nltk.corpus import stopwords\n",
        "from nltk.tokenize import word_tokenize\n",
        "from sentence_transformers import SentenceTransformer\n",
        "\n",
        "# Download required NLTK data\n",
        "nltk.download('punkt_tab')\n",
        "nltk.download('stopwords')\n",
        "\n",
        "\n",
        "class SimpleRAG:\n",
        "\n",
        "    def __init__(self):\n",
        "        # Load embedding model\n",
        "        self.model = SentenceTransformer('all-MiniLM-L6-v2')\n",
        "        self.stop_words = set(stopwords.words('english'))\n",
        "        self.index = None\n",
        "        self.documents = []\n",
        "\n",
        "    # Step 1 & 2: Preprocess Data (Remove Stopwords)\n",
        "    def preprocess(self, text):\n",
        "        words = word_tokenize(text)\n",
        "        filtered = [w for w in words if w.lower() not in self.stop_words]\n",
        "        return \" \".join(filtered)\n",
        "\n",
        "    # Step 3: Convert to Embeddings\n",
        "    def embed(self, texts):\n",
        "        return self.model.encode(texts)\n",
        "\n",
        "    # Step 4: Store in Vector DB\n",
        "    def store_documents(self, documents):\n",
        "        self.documents = [self.preprocess(doc) for doc in documents]\n",
        "        embeddings = self.embed(self.documents)\n",
        "\n",
        "        dimension = embeddings.shape[1]\n",
        "        self.index = faiss.IndexFlatL2(dimension)\n",
        "        self.index.add(np.array(embeddings))\n",
        "\n",
        "    # Step 5: Search Similar Documents\n",
        "    def search(self, query, k=2):\n",
        "        processed_query = self.preprocess(query)\n",
        "        query_vector = self.embed([processed_query])\n",
        "\n",
        "        distances, indices = self.index.search(query_vector, k)\n",
        "        results = [self.documents[i] for i in indices[0]]\n",
        "        return results\n",
        "\n",
        "    # Step 6: Generate Answer (LLM Generation)\n",
        "    def generate_answer(self, query):\n",
        "        generator = pipeline('text-generation', model='gpt2')\n",
        "        retrieved_docs = self.search(query)\n",
        "\n",
        "        context = \" \".join(retrieved_docs)\n",
        "\n",
        "        # Proper Prompt Formatting\n",
        "        prompt = f\"\"\"\n",
        "Use the following context to answer the question.\n",
        "\n",
        "Context:\n",
        "{context}\n",
        "\n",
        "Question:\n",
        "{query}\n",
        "\n",
        "Answer:\n",
        "\"\"\"\n",
        "\n",
        "        result = generator(\n",
        "            prompt,\n",
        "            max_length=300,\n",
        "            num_return_sequences=1,\n",
        "            truncation=True\n",
        "        )\n",
        "\n",
        "        return result[0]['generated_text']\n",
        "\n",
        "\n",
        "# ------------------------------\n",
        "# Sample Data\n",
        "# ------------------------------\n",
        "\n",
        "documents = [\n",
        "    \"Machine Learning (ML) is a subfield of Artificial Intelligence concerned with designing algorithms that enable systems to learn patterns from data and make decisions or predictions without being explicitly programmed with rule-based logic. Instead of hard-coding instructions, ML models infer functional relationships between input features (independent variables) and target outputs (dependent variables) by optimizing an objective function over training data. At its core, ML is about statistical estimation, optimization, and generalization.\",\n",
        "\n",
        "    \"Machine Learning is broadly categorized into Supervised Learning, Unsupervised Learning, and Reinforcement Learning. In supervised learning, labeled datasets are used to train models for tasks such as regression and classification. In unsupervised learning, the data has no labeled target variable, and the goal is to uncover hidden structures or patterns. Reinforcement learning focuses on agents interacting with an environment and learning through reward-based feedback.\",\n",
        "\n",
        "    \"A typical ML pipeline includes data collection, preprocessing, feature engineering, model selection, hyperparameter tuning, model evaluation, and deployment. Overfitting and underfitting are key concerns. Regularization techniques such as L1 and L2 help control model complexity.\",\n",
        "\n",
        "    \"Modern ML has evolved significantly with Deep Learning, where multi-layer neural networks learn hierarchical feature representations. Applications include recommendation systems, fraud detection, NLP, computer vision, healthcare diagnostics, and autonomous vehicles.\"\n",
        "]\n",
        "\n",
        "# ------------------------------\n",
        "# Run RAG\n",
        "# ------------------------------\n",
        "\n",
        "rag = SimpleRAG()\n",
        "\n",
        "# Store data\n",
        "rag.store_documents(documents)\n",
        "\n",
        "# User Query\n",
        "query = \"What is deep learning?\"\n",
        "\n",
        "# Generate Answer\n",
        "print(rag.generate_answer(query))"
      ],
      "metadata": {
        "id": "-6O045S6mJjj"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}